export const dimensiRisiko = [
  {
    risiko: "keamanan",
    indikator: [
      "Narapidana pernah berencana untuk melarikan diri dalam 6 bulan terakhir",
      "Narapidana pernah melarikan diri",
      "Narapidana mengajak orang lain untuk melarikan diri",
      "Apabila Narapidana melarikan diri ia dapat mengancam/ membahayakan orang lain, atau kelompok masyarakat di luar Lapas/ Rutan",
      "Narapidana memiliki kelompok/ jaringan di dalam Lapas/ Rutan yang suatu waktu dapat membantunya untuk melarikan diri apabila dibutuhkan",
      "Narapidana memiliki kelompok/ jaringan di luar Lapas/ Rutan yang suatu waktu dapat membantunya untuk melarikan diri apabila dibutuhkan",
    ],
  },
  {
    risiko: "keselamatan",
    indikator: [
      "Narapidana pernah melakukan tindak kekerasan kepada orang lain dalam 6 bulan terakhir",
      "Narapidana pernah terlibat dalam perkelahian secara individual yang berakibat korban meninggal, atau terluka sehingga membutuhkan perawatan medis",
      "Narapidana pernah melakukan tindak pidana dengan kekerasan sebelum berusia 18 tahun",
      "Narapidana pernah terlibat dalam perkelahian secara individual dengan menggunakan senjata tajam atau senjata api",
      "Narapidana pernah terlibat dalam perkelahian secara berkelompok terhadap individu/ kelompok lain dalam 6 bulan terakhir",
      "Narapidana pernah menjadi anggota kelompok/ organisasi/ jaringan yang melakukan tindak kekerasan di masyarakat",
      "Narapidana pernah memegang peran penting di suatu kelompok / organisasi/ jaringan yang melakukan tindak kekerasan di masyarakat",
      "Narapidana pernah mendapatkan pelatihan kemampuan militer (menggunakan senjata, merakit bom, melumpuhkan orang)",
      "Narapidana pernah menyakiti/ melukai diri sendiri dalam 6 bulan terakhir",
    ],
  },
  {
    risiko: "stabilitas",
    indikator: [
      "Narapidana pernah terlibat dalam aksi unjuk rasa di dalam Lapas/ Rutan",
      "Narapidana pernah memegang posisi penting dalam aksi unjuk rasa di luar Lapas/ Rutan (misalnya: pengorganisir, pemimpin unjuk rasa, koordinator lapangan)",
      "Narapidana pernah melakukan pelanggaran norma secara berulang di lingkungan masyarakat",
      "Narapidana pernah melakukan pelanggaran indisipliner di tempat kerja lebih dari 2kali",
      "Narapidana pernah diberhentikan dari tempat kerja karena melakukan pelanggaran (di luar kasus pidana yang sedang dijalani)",
      "Narapidana memiliki kecenderungan melawan kepada Petugas dalam 6 bulan terakhir",
      "Narapidana memiliki kecenderungan anti sosial dalam 6 bulan terakhir",
      "Narapidana pernah melanggar aturan di Lapas/Rutan dalam 6 bulan terakhir",
    ],
  },
  {
    risiko: "kemasyarakatan",
    indikator: [
      "Narapidana merupakan anggota aktif dari kelompok/ jaringan yang berpotensi melakukan kegiatan melawan hukum",
      "Narapidana pernah/ masih menjadi anggota/ partisan dari kelompok/ organisasi massa berbasis kesukuan/ etnis/ kekeluargaan/ marga yang melawan hukum  ",
      "Narapidana pernah atau masih menjadi anggota/ partisan dari partai politik yang memiliki pengaruh untuk melanggar aturan/ melawan hukum",
      "Narapidana memiliki pengaruh adat/ budaya/ sosial/ ekonomi yang besar untuk melanggar aturan/ melawan hukum",
      "Narapidana merupakan tokoh agama yang memiliki pengaruh untuk melanggar aturan/ melawan hukum",
      "Narapidana memiliki kekuatan berdasarkan posisinya dalam organisasi kriminal",
      "Narapidana memiliki kekuatan berdasarkan posisinya dalam kelompok separatisme",
      "Narapidana memiliki kekuatan berdasarkan posisinya dalam kelompok/ organisasi fundamentalis/ ekstrimis berbasis agama",
    ],
  },
];

export const pendidikan = [
  "SD",
  "SLTP/SMP",
  "SLTA/SMA",
  "S1",
  "S2",
  "S3",
  "Tidak Sekolah",
];

export const tindakPidana = {
  jenis: [
    "Farmasi dan Kesehatan",
    "Fidusia (Pengalihan hak kepemilikan)",
    "Illegal Logging/Pembakaran liar",
    "ITE Informasi dan Transaksi Elektronik)",
    "Jinayat",
    "KDRT (Kekerasan dalam Rumah Tangga)",
    "Kealfaan mengakibatkan kematian/luka",
    "Kehutanan",
    "Keimigrasian",
    "Kejahatan Hak Cipta",
    "Kejahatan Merek",
    "Kejahatan terhadap asal usul perkawinan",
    "Kejahatan terhadap HAM",
    "Kejahatan terhadap keamanan negara (subversi)",
    "Kejahatan terhadap kemerdekaan orang lain",
    "Kejahatan terhadap Kesusilaan",
    "Kejahatan terhadap Keteriban Umum",
    "Kepabeanan",
    "Ketenagakerjaan",
    "Konservasi Sumber Daya Alam",
    "Korupsi",
    "Lalu Lintas",
    "Lingkungan Hidup",
    "Mata Uang",
    "Migas",
    "Narkotika & Psikotropika (Pemakai/Pengguna)",
    "Narkotika & Psikotropika (Penjual/Pengedar)",
    "Pangan",
    "Paten",
    "Pelayaran",
    "Pemalsuan",
    "Pembunuhan",
    "Pemerasaan, Pengancaman, Penculikan dan Perampokan",
    "Pemerintah Daerah",
    "Penadahan",
    "Pencucian Uang",
    "Pencurian",
    "Penempatan dan Perlindungan TKI",
    "Penganiayaan",
    "Pengelolaan Wilayah Pesisir",
    "Penggelapan",
    "Penghinaan",
    "Penipuan",
    "Penyiaran",
    "Peradilan Anak / ABH",
    "Perbankan",
    "Perdagangan Orang",
    "Perikanan",
    "Perjudian",
    "Perlindungan Anak",
    "Perpajakan",
    "Pertambangan",
    "Perumahan dan Pemukiman",
    "Perusakan dan Pembakaran",
    "Pidsus Cukai",
    "Pidsus Kehutanan",
    "Pidsus Pendidikan",
    "Pidsus Pra Peradilan",
    "Pidsus Terorisme",
    "Pornografi",
    "Pra Peradilan",
    "Rahasia Dagang",
    "Senjata Api, Senjata Tajam dan Bahan Peledak",
    "Sumpah Palsu dan Keterangan Palsu",
    "Tindak Pidana Ekonomi",
    "Uang Palsu dan Penggandaan",
  ],
  nilai: [
    0.61, 0.51, 0.64, 0.59, 0.46, 0.57, 0.47, 0.53, 0.53, 0.51, 0.51, 0.42,
    0.69, 0.42, 0.74, 0.75, 0.55, 0.5, 0.49, 0.54, 0.77, 0.36, 0.64, 0.6, 0.59,
    0.44, 0.88, 0.54, 0.53, 0.49, 0.51, 0.85, 0.71, 0.52, 0.45, 0.69, 0.5, 0.65,
    0.55, 0.55, 0.49, 0.46, 0.54, 0.56, 0.59, 0.64, 0.73, 0.56, 0.35, 0.64,
    0.62, 0.62, 0.51, 0.46, 0.52, 0.54, 0.42, 0.41, 0.94, 0.76, 0.4, 0.52, 0.8,
    0.49, 0.6, 0.58,
  ],
};
