export const pokokA = [
  "Pertama kali ditahan atau melakukan pelanggaran berusia 12 tahun",
  "Melakukan tindak pidana dalam kurun waktu 5 tahun (sebelum tindak pidana saat ini)",
  "Usia pada saat melakukan tindak pidana yang sekarang",
  "Pidana berkaitan dengan",
  "Apakah Anak melakukan pelanggaran selama proses peradilan/ program pembinaan",
  "Pendidikan tertinggi hingga tamat",
  "Status pekerjaan sebelum pemidanaan yang sekarang ",
  "Hubungan dengan orang tua atau wali",
  "Memiliki hubungan dengan teman/ kerabat yang terlibat tindak kriminal di masyarakat",
  "Pandangan Anak terhadap pidana yang sekarang",
];

export const jawabanA = [
  "Ya",
  "Tidak",
  "Pertama kali melakukan",
  "1 kali",
  "2 kali",
  "3 kali",
  "3 kali lebih",
  "12-13",
  "14-15",
  "16-17",
  "17 ke atas",
  "Kategori A (Penadahan, Pengerusakan, Perkelahian, Pelanggaran Lalu Lintas, Kepemilikan Senjata Tajam, Cyber Crime)",
  "Kategori B (Penculikan, Penggelapan)",
  "Kategori C (Perdagangan Orang, Perjudian, KDRT)",
  "Kategori D (Penganiayaan, Pencurian, Pemerasan, Penipuan)",
  "Kategori E (Perampokan, Narkotika, Pelecehan dan Penyimpangan Seksual, Terorisme, Pembunuhan) ",
  "Tidak Pernah",
  "Pernah",
  "Jarang",
  "Sering",
  "Sering Sekali",
  "SD tidak lulus",
  "SD lulus",
  "SMP tidak lulus",
  "SMP lulus",
  "SMA",
  "Pelajar",
  "Pekerja",
  "Wirausaha",
  "Menganggur",
  "Baik (akrab)",
  "Cukup Baik (biasa)",
  "Kurang Baik (jaga jarak)",
  "Tidak Baik/ Buruk (putus)",
  "Tidak ada",
  "Tidak akrab",
  "Akrab",
  "Sangat akrab (Sahabat)",
  "Kriminal tidak dapat diterima/ Kriminal adalah perbuatan yang salah",
  "Kriminal mungkin dapat diterima",
  "Kriminal adalah perbuatan yang benar/ dapat diterima",
  "Kriminal murni direncanakan",
  "Kriminal sebagai kebiasaan/ pekerjaan",
];

export const kunciA = [
  "4",
  "1",
  "0",
  "1",
  "2",
  "3",
  "4",
  "1",
  "2",
  "3",
  "4",
  "0",
  "1",
  "2",
  "3",
  "4",
  "0",
  "1",
  "2",
  "3",
  "4",
  "0",
  "1",
  "2",
  "3",
  "4",
  "1",
  "2",
  "3",
  "4",
  "1",
  "2",
  "3",
  "4",
  "1",
  "2",
  "3",
  "4",
  "0",
  "1",
  "2",
  "3",
  "4",
];

export const pokokB = [
  "Kemampuan pola asuh orangtua (terkait dengan kemampuan menjamin)",
  "Pihak yang melakukan peran pendampingan, pengawasan, perhatian, perlindungan sebelum terjadinya tindak pidana",
];

export const jawabanB = [
  "Tidak Mampu",
  "Kurang Mampu",
  "Cukup Mampu",
  "Mampu",
  "Orang tua/ Wali/ Lembaga/ Badan Sosial",
  "Masyarakat",
  "Sekolah",
];

export const kunciB = ["0", "1", "2", "3", "0", "1", "2"];

export const indikator1 = [
  "1.Tidak menyelesaikan pendidikan akhir",
  "2.Tidak mengenyam bangku sekolah",
  "3.Tidak mampu menulis/ membaca",
  "4.Tidak memiliki keterampilan",
  "5.Pernah di-skors atau dikeluarkan dari sekolah karena alasan tidak disiplin",
  "6.Sudah tidak banyak aktivitas selama lebih dari 12 bulan",
  "7.Tidak aktif ketika di masyarakat/ sekolah",
  "8.Kesulitan mencari pekerjaan atau mempertahankan pekerjaan",
  "9.Tidak akur dengan atasan di tempat kerja/ guru di sekolah",
  "10.Tidak akur dengan sesama teman kerja/ murid",
  "11.Prestasi yang buruk di sekolah/ tempat kerja",
  "12.Tidak ada/ sedikit keterampilan kerja",
];

export const indikator2 = [
  "13.Penggunaan narkoba, alkohol, dan zat adiktif lainnya menyebabkan masalah dalam keluarga.",
  "14.Penggunaan narkoba, alkohol, dan zat adiktif lainnya menyebabkan masalah di lingkungan pergaulan, sekolah atau tempat kerja.",
  "15.Apakah anak memiliki sejarah “penyalahgunaan obat- obatan, alkohol, dan zat adiktif lainnya” dalam jangka panjang, atau di masa lalu.",
  "16.Narkoba, alkohol, dan zat adiktif lainnya menyebabkan masalah medis bagi Anak.",
];

export const indikator3 = [
  "17.Orangtua/ wali/ keluarga tidak memiliki kemampuan finansial untuk memenuhi kebutuhan Anak",
  "18.Menjadi tulang punggung ekonomi keluarga",
  "19.Memiliki hutang pribadi saat ini",
  "20.Memiliki hutang keluarga yang dibebankan kepada Anak saat ini",
  "21.Anak tidak mengikuti kegiatan, organisasi terstruktur pada saat sebelum pidana.",
  "22.Anak memiliki terlalu banyak waktu luang di masyarakat",
];

export const indikator4 = [
  "23.Hubungan yang bermasalah dengan keluarga/teman sebaya/ lingkungan pada masa menjelang tindak pidana.",
  "24.Anggota keluarga pernah terlibat dalam kegiatan kriminal.",
  "25.Teman atau rekan pernah terlibat dalam kegiatan kriminal.",
  "26.Anggota keluarga memiliki riwayat penyalahgunaan narkotika, obat-obatan, alkohol, atau zat adiktif lainnya",
  "27.Anggota keluarga memiliki riwayat kecanduan narkotika, obat-obatan, alkohol, atau zat adiktif lainnya",
  "28.Tidak memiliki teman-teman yang pro-sosial (non-kriminal)",
  "29.Tindak pidana dilakukan bersama orang lain.",
  "30.Pergaulan selama proses peradilan/ pembinaan mengakibatkan Anak menjadi lebih bermasalah.",
];

export const indikator5 = [
  "31.Menunjukan sikap yang tidak sesuai dengan norma di masyarakat.",
  "32.Percaya bahwa pelanggaran/kejahatan adalah metode yang sah atau diperlukan untuk memenuhi kebutuhan.",
  "33.Sedikit atau tidak ada rasa iba/kasihan terhadap para korban kejahatan.",
  "34.Menunjukan sikap penolakan terhadap peraturan dan norma hukum.",
  "35.Menunjukan sikap penolakan terhadap pembinaan untuk memperbaiki perilaku kriminal.",
];

export const indikator6 = [
  "36.Memiliki masalah berjudi (online, kartu, dll) dan atau kecanduan lainnya (kartu/ game online/ pornografi/ mengutil)",
  "37.Memiliki masalah dalam pengendaliana emosi dan konflik dalam keluarga.",
  "38.Pelaku pidana asusila.",
  "39.Bergabung dalam jaringan kriminal atau geng.",
  "40.Tindak pidana terorganisir/ tindak pidana atas kebencian/ tindak pidana terorisme",
  "41.Kurangnya dukungan keluarga atau masyarakat.",
  "42.Berada dibawah ancaman orang lain.",
];
